### ISSUE TITLE
App drawer crashing

### ISSUE THREAD

**Issue by emoki69** [albu-razvan/Stario#47] opened 2024-11-06 08:48 UTC
**Describe the bug**
I downloaded the latest version, i believe the 2.4 alpha, as i launch it everything is alright but when i swipe up to open my app drawer the app crashes, i open the app a second time and open the drawer and i get notification that the app has a bug and samsung reccomends to clear cache, so i do it and it still crashes

**To Reproduce**
Steps to reproduce:
1. Open Stario launcher
2. Scroll up for app drawer
3. Stario Launcher crashes

**Expected behaviour**
To open the app drawer

**Screenshots**
![Screenshot_20241106_104717_One UI Home](https://github.com/user-attachments/assets/d5db382b-8f29-4ea8-a6b6-6992a30581ff)

**Smartphone (please complete the following information):**
 - Device: Samsung S24 Ultra
 - OS: OneUi 6.1
 - Version 2.4 alpha

**Additional context**

**Comment by albu-razvan** [comment] 2024-11-10 11:31
Duplicate of #36

**Closed by albu-razvan** 2024-11-10 11:31 UTC
