### ISSUE TITLE
Crashing in the app list

### ISSUE THREAD

**Issue by Caco-o-sapo** [albu-razvan/Stario#22] opened 2024-08-24 22:31 UTC
**Describe the bug**
When I try to open the app list it crashes almost every time. 

**To Reproduce**
Steps to reproduce:
1. Open Stario
2. Scroll to the app list 
3. Wait for it to load

**Expected behaviour**
It should stay open and not crash

**Screenshots**
https://github.com/user-attachments/assets/7cb6e931-7c92-4c61-97ef-dfa23fa99b40

**Smartphone (please complete the following information):**
 - Device: Samsung A14 5g
 - OS: Android
 - Version 14

**Additional context**
Nothing to add.

**Comment by Caco-o-sapo** [comment] 2024-08-24 22:32
It's me Mortimer btw

**Comment by albu-razvan** [comment] 2024-08-25 18:48
Duplicate of #20 _(same exception cause)_

**Closed by albu-razvan** 2024-08-25 18:48 UTC
Labels: duplicate
